image: alpine:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  TERRAFORM_VERSION: "1.5.7"
  SOPS_VERSION: "3.7.3"  # Specify your desired SOPS version

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - apk add --no-cache curl gnupg
  - curl -fsSL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -o terraform.zip
  - unzip terraform.zip
  - mv terraform /usr/local/bin/
  - curl -fsSL https://github.com/mozilla/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux -o sops
  - chmod +x sops
  - mv sops /usr/local/bin/
  - echo "${SOPS_GPG_KEY}" | gpg --import
  - cd ${TF_ROOT}
  - sops -d terraform.tfvars.enc > terraform.tfvars
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -var-files="terraform.tfvars" -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform apply -var-files="terraform.tfvars" -auto-approve tfplan
  when: manual
  only:
    - main  # or your default branch