image: ubuntu:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  TERRAFORM_VERSION: "1.9.3"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform
    - ${TF_ROOT}/.terraform.lock.hcl

before_script:
  - apt-get update && apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform version
  - cd ${TF_ROOT}

stages:
  - backend-init
  - init
  - validate
  - plan
  - apply
  - destroy

backend-init:
    stage: backend-init
    script:
      - terraform init -backend-config=backend.tf
    when: manual

init:
    stage: init
    script:
        - terraform init
    artifacts:
        paths:
        - ${TF_ROOT}/.terraform
        - ${TF_ROOT}/.terraform.lock.hcl

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan -out=tfplan
    artifacts:
        paths:
          - tfplan

apply:
    stage: apply
    script:
        - terraform apply -auto-approve tfplan 
    when: manual
    only: 
        - main

destroy:
    stage: destroy
    script:
        - terraform destroy -auto-approve
    when: manual
    only:
        - main