image: ubuntu:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  TERRAFORM_VERSION: "1.9.3"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - apt-get update && apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform version
  - cd ${TF_ROOT}
  - rm -rf .terraform/providers
  - terraform init -backend-config="key=terraform-state/${TF_STATE_NAME}" -upgrade

stages:
  - validate
  - plan
  - apply

validate:
    stage: validate
    script:
        - terraform validate

plan:
    stage: plan
    script:
        - terraform plan -out=tfplan
    artifacts:
        paths:
          - tfplan

apply:
    stage: apply
    script:
        - terraform apply -auto-approve tfplan 
    when: manual
    only: 
        - main