image: ubuntu:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}
  TF_STATE_NAME: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  TERRAFORM_VERSION: "1.9.3"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - apt-get update && apt-get install -y wget unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform version
  - cd ${TF_ROOT}
  - rm -rf .terraform
  - rm -f .terraform.lock.hcl

stages:
  - init
  - validate
  - plan
  - apply

init:
  stage: init
  script:
    - terraform init -reconfigure -backend-config="bucket=${TF_STATE_S3_BUCKET}" -backend-config="key=${TF_STATE_NAME}" -backend-config="region=${AWS_DEFAULT_REGION}"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  script:
    - terraform show tfplan
    - terraform apply -auto-approve tfplan 
  when: manual
  only: 
    - main